spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: mongo
#  redis:
#    host: 192.168.10.134
logging:
  level:
    com.earnest: debug

app:
  spider:
    enable: false
  proxy-pool:
    enable: false