spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://144.202.120.233:3306/j_video?characterEncoding=utf8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update