spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: mongo
#  redis:
#    host: 192.168.10.129
logging:
  level:
    com.earnest: debug
    org .springframework.data.mongodb.core: debug

spider:
  enable: false
